services:
  kindle-app:
    image: nginx:alpine
    container_name: kindle-app
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external: true
