services:
  kindle-app:
    image: nginx:alpine
    container_name: kindle-app
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external: true
