server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(appcache|manifest)$ {
        add_header Content-Type text/cache-manifest;
    }

    location ~* \.html$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(css|js|json|png|webp)$ {
        expires 365d;
        add_header Cache-Control "public, immutable, must-revalidate";
    }
}
